version: "2.2"

services:
  telegraf:
    image: telegraf:latest
    restart: always
    volumes:
      # Mount for telegraf config
      - /data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    command: --input-filter modbus
    mem_limit: 100M

  influxdb:
    image: influxdb:latest
    environment: 
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
      - INFLUXDB_ADMIN_PASSWORD=secret
      - INFLUXDB_DB=telegraf
    volumes:
      - "influx-data:/var/lib/influxdb:rw"
      - "influx-config:/etc/influxdb:rw"
    restart: always
    mem_limit: 500M

  grafana:
    build:
      context: grafana
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - influxdb
    volumes:
      - "grafana:/var/lib/grafana:rw"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - INFLUXDB_ADMIN_PASSWORD=secret
    restart: always
    mem_limit: 500M

volumes:
  grafana:
  influx-data:
  influx-config:
